name: Performance Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y gnupg2 && curl -s https://dl.k6.io/key.gpg | sudo apt-key add - && echo 'deb https://dl.k6.io/deb stable main' | sudo tee /etc/apt/sources.list.d/k6.list && sudo apt-get update && sudo apt-get install -y k6
      - name: Run smoke test
        run: K6_ENV=dev k6 run src/tests/smoke/smokeTest.js
